const mongoose = require('mongoose')

const MonsterSchema = new mongoose.Schema({
    name: { type: String, required: true, unique: true },
    slug: { type: String, required: true, unique: true },
    image: String,
    size: String,
    type: String,
    alignment: String,
    ac: String,
    hp: String,
    speed: String,
    burrowSpeed: String,
    climbSpeed: String,
    flySpeed: String,
    swimSpeed: String,
    str: String,
    dex: String,
    con: String,
    int: String,
    wis: String,
    cha: String,
    savingThrows: String,
    skills: String,
    resistances: String,
    damageImmunities: String,
    conditionImmunities: String,
    vulnerabilities: String,
    senses: String,
    languages: String,
    cr: String,
    proficiencyBonus: String,
    abilityOne: String,
    abilityTwo: String,
    abilityThree: String,
    abilityFour: String,
    abilityFive: String,
    actionOne: String,
    actionTwo: String,
    actionThree: String,
    actionFour: String,
    actionFive: String,
    bonusActionOne: String,
    bonusActionTwo: String,
    bonusActionThree: String,
    bonusActionFour: String,
    bonusActionFive: String,
    reactionOne: String,
    reactionTwo: String,
    reactionThree: String,
    reactionFour: String,
    reactionFive: String,
    legendaryActionOne: String,
    legendaryActionTwo: String,
    legendaryActionThree: String,
    legendaryActionFour: String,
    legendaryActionFive: String,
    lairActionOne: String,
    lairActionTwo: String,
    lairActionThree: String,
    lairActionFour: String,
    lairActionFive: String,
    mythicActionOne: String,
    mythicActionTwo: String,
    mythicActionThree: String,
    mythicActionFour: String,
    mythicActionFive: String,
    regionalAbilityOne: String,
    regionalAbilityTwo: String,
    regionalAbilityThree: String,
    regionalAbilityFour: String,
    regionalAbilityFive: String,
    description: String,
},  {timestamps: true})

const Monster = mongoose.model("Monster", MonsterSchema)

module.exports = Monster